package registry

var builtinResources = []Resource{
	{
		Plural: "incidents", Singular: "incident", Aliases: []string{"inc"},
		Table: "incident", Category: "ITSM",
		Description:     "ITSM Incident records",
		IdentifierField: "number",
		DefaultColumns: []Column{
			{Header: "NUMBER", Field: "number", Width: 14},
			{Header: "STATE", Field: "state", Width: 12},
			{Header: "PRIORITY", Field: "priority", Width: 8},
			{Header: "SHORT DESCRIPTION", Field: "short_description", Width: 50},
			{Header: "ASSIGNED TO", Field: "assigned_to", Width: 20},
			{Header: "UPDATED", Field: "sys_updated_on", Width: 19},
		},
		FieldAliases: map[string]string{
			"description": "short_description",
			"assignee":    "assigned_to",
			"group":       "assignment_group",
		},
	},
	{
		Plural: "changes", Singular: "change", Aliases: []string{"chg"},
		Table: "change_request", Category: "ITSM",
		Description:     "Change Request records",
		IdentifierField: "number",
		DefaultColumns: []Column{
			{Header: "NUMBER", Field: "number", Width: 14},
			{Header: "TYPE", Field: "type", Width: 10},
			{Header: "STATE", Field: "state", Width: 12},
			{Header: "SHORT DESCRIPTION", Field: "short_description", Width: 50},
			{Header: "ASSIGNED TO", Field: "assigned_to", Width: 20},
			{Header: "UPDATED", Field: "sys_updated_on", Width: 19},
		},
		FieldAliases: map[string]string{
			"description": "short_description",
			"assignee":    "assigned_to",
			"group":       "assignment_group",
		},
	},
	{
		Plural: "problems", Singular: "problem", Aliases: []string{"prb"},
		Table: "problem", Category: "ITSM",
		Description:     "Problem records",
		IdentifierField: "number",
		DefaultColumns: []Column{
			{Header: "NUMBER", Field: "number", Width: 14},
			{Header: "STATE", Field: "state", Width: 12},
			{Header: "PRIORITY", Field: "priority", Width: 8},
			{Header: "SHORT DESCRIPTION", Field: "short_description", Width: 50},
			{Header: "ASSIGNED TO", Field: "assigned_to", Width: 20},
			{Header: "UPDATED", Field: "sys_updated_on", Width: 19},
		},
		FieldAliases: map[string]string{
			"description": "short_description",
			"assignee":    "assigned_to",
			"group":       "assignment_group",
		},
	},
	{
		Plural: "requests", Singular: "request", Aliases: []string{"req"},
		Table: "sc_request", Category: "ITSM",
		Description:     "Service Catalog Request records",
		IdentifierField: "number",
		DefaultColumns: []Column{
			{Header: "NUMBER", Field: "number", Width: 14},
			{Header: "STATE", Field: "request_state", Width: 12},
			{Header: "SHORT DESCRIPTION", Field: "short_description", Width: 50},
			{Header: "REQUESTED FOR", Field: "requested_for", Width: 20},
			{Header: "OPENED", Field: "sys_created_on", Width: 19},
		},
	},
	{
		Plural: "request-items", Singular: "request-item", Aliases: []string{"ritm"},
		Table: "sc_req_item", Category: "ITSM",
		Description:     "Request Item records",
		IdentifierField: "number",
		DefaultColumns: []Column{
			{Header: "NUMBER", Field: "number", Width: 14},
			{Header: "STATE", Field: "state", Width: 12},
			{Header: "SHORT DESCRIPTION", Field: "short_description", Width: 50},
			{Header: "ASSIGNED TO", Field: "assigned_to", Width: 20},
			{Header: "UPDATED", Field: "sys_updated_on", Width: 19},
		},
	},
	{
		Plural: "tasks", Singular: "task",
		Table: "task", Category: "ITSM",
		Description:     "Task records",
		IdentifierField: "number",
		DefaultColumns: []Column{
			{Header: "NUMBER", Field: "number", Width: 14},
			{Header: "STATE", Field: "state", Width: 12},
			{Header: "PRIORITY", Field: "priority", Width: 8},
			{Header: "SHORT DESCRIPTION", Field: "short_description", Width: 50},
			{Header: "ASSIGNED TO", Field: "assigned_to", Width: 20},
		},
	},
	{
		Plural: "users", Singular: "user", Aliases: []string{"usr"},
		Table: "sys_user", Category: "Platform",
		Description:     "User records",
		IdentifierField: "user_name",
		DefaultColumns: []Column{
			{Header: "USER NAME", Field: "user_name", Width: 16},
			{Header: "NAME", Field: "name", Width: 25},
			{Header: "EMAIL", Field: "email", Width: 30},
			{Header: "DEPARTMENT", Field: "department", Width: 20},
			{Header: "ACTIVE", Field: "active", Width: 6},
		},
	},
	{
		Plural: "groups", Singular: "group", Aliases: []string{"grp"},
		Table: "sys_user_group", Category: "Platform",
		Description:     "User Group records",
		IdentifierField: "name",
		DefaultColumns: []Column{
			{Header: "NAME", Field: "name", Width: 30},
			{Header: "DESCRIPTION", Field: "description", Width: 40},
			{Header: "MANAGER", Field: "manager", Width: 20},
			{Header: "ACTIVE", Field: "active", Width: 6},
		},
	},
	{
		Plural: "cis", Singular: "ci",
		Table: "cmdb_ci", Category: "CMDB",
		Description:     "Configuration Item records",
		IdentifierField: "name",
		DefaultColumns: []Column{
			{Header: "NAME", Field: "name", Width: 30},
			{Header: "CLASS", Field: "sys_class_name", Width: 20},
			{Header: "STATUS", Field: "operational_status", Width: 12},
			{Header: "ENVIRONMENT", Field: "environment", Width: 14},
			{Header: "UPDATED", Field: "sys_updated_on", Width: 19},
		},
	},
	{
		Plural: "servers", Singular: "server", Aliases: []string{"srv"},
		Table: "cmdb_ci_server", Category: "CMDB",
		Description:     "Server CI records",
		IdentifierField: "name",
		DefaultColumns: []Column{
			{Header: "NAME", Field: "name", Width: 25},
			{Header: "IP ADDRESS", Field: "ip_address", Width: 15},
			{Header: "OS", Field: "os", Width: 15},
			{Header: "STATUS", Field: "operational_status", Width: 12},
			{Header: "ENVIRONMENT", Field: "environment", Width: 14},
		},
	},
	{
		Plural: "applications", Singular: "application", Aliases: []string{"app"},
		Table: "cmdb_ci_appl", Category: "CMDB",
		Description:     "Application CI records",
		IdentifierField: "name",
		DefaultColumns: []Column{
			{Header: "NAME", Field: "name", Width: 30},
			{Header: "VERSION", Field: "version", Width: 12},
			{Header: "STATUS", Field: "operational_status", Width: 12},
			{Header: "ENVIRONMENT", Field: "environment", Width: 14},
			{Header: "UPDATED", Field: "sys_updated_on", Width: 19},
		},
	},
	{
		Plural: "services", Singular: "service", Aliases: []string{"svc"},
		Table: "cmdb_ci_service", Category: "CMDB",
		Description:     "Service CI records",
		IdentifierField: "name",
		DefaultColumns: []Column{
			{Header: "NAME", Field: "name", Width: 30},
			{Header: "STATUS", Field: "operational_status", Width: 12},
			{Header: "OWNED BY", Field: "owned_by", Width: 20},
			{Header: "ENVIRONMENT", Field: "environment", Width: 14},
			{Header: "UPDATED", Field: "sys_updated_on", Width: 19},
		},
	},
	{
		Plural: "kb-articles", Singular: "kb-article", Aliases: []string{"kb"},
		Table: "kb_knowledge", Category: "Platform",
		Description:     "Knowledge Base articles",
		IdentifierField: "number",
		DefaultColumns: []Column{
			{Header: "NUMBER", Field: "number", Width: 14},
			{Header: "SHORT DESCRIPTION", Field: "short_description", Width: 50},
			{Header: "WORKFLOW", Field: "workflow_state", Width: 12},
			{Header: "CATEGORY", Field: "kb_category", Width: 20},
			{Header: "UPDATED", Field: "sys_updated_on", Width: 19},
		},
	},
	{
		Plural: "catalog-items", Singular: "catalog-item", Aliases: []string{"catitem"},
		Table: "sc_cat_item", Category: "Platform",
		Description:     "Service Catalog Item records",
		IdentifierField: "name",
		DefaultColumns: []Column{
			{Header: "NAME", Field: "name", Width: 30},
			{Header: "CATEGORY", Field: "category", Width: 20},
			{Header: "SHORT DESCRIPTION", Field: "short_description", Width: 40},
			{Header: "ACTIVE", Field: "active", Width: 6},
		},
	},
}
